#!/bin/bash



# Function to check if the expiry of a secret is less than one year

function check_expiry() {

    expiry=$(az keyvault secret show --vault-name $1 --name $2 --query 'attributes.expires' -o tsv)

    if [ ! -z "$expiry" ]; then

        current=$(date +%s)

        expiry=$(date -d "$expiry" +%s)

        difference=$(( ($expiry - $current) / (60*60*24) ))

        if [ $difference -lt 365 ]; then

            return 0 # Return true if expiry is less than one year

        fi

    fi

    return 1 # Return false otherwise

}



# Function to set expiry for a secret if it doesn't already have one

function set_expiry() {

    if ! check_expiry $1 $2; then

        az keyvault secret set-attributes --vault-name $1 --name $2 --expires $(date -d "+1 year" +%Y-%m-%dT%H:%MZ) > /dev/null

        echo "Expiry set for secret $2 in Key Vault $1"

    else

        echo "Skipping secret $2 in Key Vault $1 as it already has an expiry less than one year"

    fi

}



# Main script



# Replace these values with your Key Vault name and list of secrets

keyvault_name="your-keyvault-name"

secrets=("secret1" "secret2" "secret3")



# Loop through each secret and set expiry

for secret in "${secrets[@]}"; do

    set_expiry $keyvault_name $secret

done

